language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

os:
  - linux
#  - osx
#branches:
#  only:
#    - /^build/

after_success:
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest Devel::Cover::Report::Codecov
  - cover -test -report coveralls
  - cover -test -report codecov