install:
  - ppm install dmake
  - ppm install Devel-CheckLib
  - cpan install CPAN
  - cpan install "Data::Validate::URI"
  #- ppm install NetAddr-IP
  #- ppm install Data-Validate-IP
  #- ppm install Net-Domain-TLD
  #- ppm install Data-Validate-Domain
  #- ppm install Data-Validate-URI
  #- ppm install JSON-MaybeXS
build_script:
  - perl Makefile.PL
  - dmake

test_script:
  - dmake test

#clone_depth: 5